Add is_oss_ok
add is_oss_ok, keep is_ok not changed

diff --git a/bin/n b/bin/n
--- a/bin/n
+++ b/bin/n
@@ -356,19 +356,29 @@ erase_line() {
 #
 # Check if the HEAD response of <url> is 200.
 #
-
 is_ok() {
   if command -v curl > /dev/null; then
-    if $GET -Is $1 | head -n 1 | grep '3..' > /dev/null; then
-      is_ok $GET -Is $1 | grep Location | awk -F ': ' '{print $2}'
+    $GET -Is $1 | head -n 1 | grep 200 > /dev/null
+  else
+    $GET -S --spider 2>&1 $1 | head -n 1 | grep 200 > /dev/null
+  fi
+}
+
+#
+# Check if the OSS(Object Storage Service) mirror is ok.
+#
+is_oss_ok() {
+  if command -v curl > /dev/null; then
+    if $GET -Is $1 | head -n 1 | grep 302 > /dev/null; then
+      is_oss_ok $GET -Is $1 | grep Location | awk -F ': ' '{print $2}'
     else
-      $GET -Is $1 | head -n 1 | grep '2..' > /dev/null
+      $GET -Is $1 | head -n 1 | grep 200 > /dev/null
     fi
   else
-    if $GET -S --spider 2>&1 $1 | head -n 1 | grep '3..' > /dev/null; then
-      is_ok $GET -S --spider 2>&1 $1 | grep Location | awk -F ': ' '{print $2}'
+    if $GET -S --spider 2>&1 $1 | head -n 1 | grep 302 > /dev/null; then
+      is_oss_ok $GET -S --spider 2>&1 $1 | grep Location | awk -F ': ' '{print $2}'
     else
-      $GET -S --spider 2>&1 $1 | head -n 1 | grep '2..' > /dev/null
+      $GET -S --spider 2>&1 $1 | head -n 1 | grep 200 > /dev/null
     fi
   fi
 }
@@ -507,7 +517,7 @@ install() {
   log install ${BINS[$DEFAULT]}-v$version
 
   local url=$(tarball_url $version)
-  is_ok $url || abort "invalid version $version"
+  is_ok $url || is_oss_ok $url || abort "invalid version $version"
 
   log mkdir $dir
   mkdir -p $dir
