add colons to reduce ambiguity

diff --git a/bin/n b/bin/n
--- a/bin/n
+++ b/bin/n
@@ -539,7 +539,7 @@ install() {
       | egrep ^$version \
       | tail -n1)
 
-    test $version || abort "invalid version ${1#v}"
+    test $version || abort "invalid version: ${1#v}"
   fi
 
   local dir=${VERSIONS_DIR[$DEFAULT]}/$version
@@ -557,7 +557,7 @@ install() {
   log install ${BINS[$DEFAULT]}-v$version
 
   local url=$(tarball_url $version)
-  is_ok $url || is_oss_ok $url || abort "invalid version $version"
+  is_ok $url || is_oss_ok $url || abort "invalid version: $version"
 
   log mkdir $dir
   mkdir -p $dir
