swap echo for printf. closes #44

diff --git a/bin/n b/bin/n
--- a/bin/n
+++ b/bin/n
@@ -11,7 +11,7 @@ VERSIONS_DIR=$N_PREFIX/n/versions
 #
 
 log() {
-  echo "\033[90m...\033[0m $@"
+  echo "\e[90m...\e[0m $@\n"
 }
 
 #
@@ -19,7 +19,7 @@ log() {
 #
 
 abort() {
-  echo "\033[31mError: $@\033[0m" && exit 1
+  printf "\e[31mError: $@\e[0m\n" && exit 1
 }
 
 # setup
@@ -112,9 +112,9 @@ display_versions() {
     local version=${dir##*/}
     local config=`test -f $dir/.config && cat $dir/.config`
     if test "$version" = "$active"; then
-      echo "  \033[32mο\033[0m $version \033[90m$config\033[0m"
+      printf "  \e[32mο\e[0m $version \e[90m$config\e[0m\n"
     else
-      echo "    $version \033[90m$config\033[0m"
+      printf "    $version \e[90m$config\e[0m\n"
     fi
   done
 }
@@ -290,12 +290,12 @@ list_versions() {
 
   for v in $versions; do
     if test "$active" = "$v"; then
-      echo "  \033[32mο\033[0m $v \033[0m"
+      printf "  \e[32mο\e[0m $v \e[0m\n"
     else
       if test -d $VERSIONS_DIR/$v; then
-        echo "  * $v \033[0m"
+        printf "  * $v \e[0m\n"
       else
-        echo "    $v"
+        printf "    $v\n"
       fi
     fi
   done
