WIP: Scan package.json last (#644)
* Scan for package.json after other files (as engine)

* Add engine to help, remove chakra from code.

* Rework auto tests with best practice BATS patterm. Simpler and ignores trace logging.

* Same-line local masking possible command  error

* Oops, remove denugging

diff --git a/bin/n b/bin/n
--- a/bin/n
+++ b/bin/n
@@ -222,7 +222,7 @@ function is_lts_codename() {
 
 function is_download_folder() {
   # e.g. nightly
-  [[ "$1" =~ ^(chakracore-nightly|chakracore-rc|chakracore-release|next-nightly|nightly|rc|release|test|v8-canary)$ ]]
+  [[ "$1" =~ ^(next-nightly|nightly|rc|release|test|v8-canary)$ ]]
 }
 
 #
@@ -373,10 +373,11 @@ Versions:
     lts               Newest Long Term Support official release
     latest, current   Newest official release
     auto              Read version from file: .n-node-version, .node-version, .nvmrc, or package.json
+    engine            Read version from package.json
     boron, carbon     Codenames for release streams
     lts_latest        node support aliases
 
-    and nightly, chakracore-release/latest, rc/10 et al
+    and nightly, rc/10 et al
 
 EOF
 }
@@ -684,7 +685,6 @@ install() {
     fi
   fi
 
-  echo
   log installing "${g_mirror_folder_name}-v$version"
 
   local url="$(tarball_url "$version")"
@@ -709,7 +709,6 @@ install() {
   if "$ACTIVATE" ; then
     activate "${g_mirror_folder_name}/$version"
   fi
-  echo
 }
 
 #
@@ -969,6 +968,7 @@ function display_package_engine_version() {
   range="$(node -e "package = require('${filepath}'); if (package && package.engines && package.engines.node) console.log(package.engines.node)")"
   trace_log "read" "${range}"
   if [[ -z "${range}" || "*" == "${range}" ]]; then
+    trace_log "target" "current"
     echo "current"
     return
   fi
@@ -983,6 +983,7 @@ function display_package_engine_version() {
       \~) [[ "${version}" =~ ^([0-9]+\.[0-9]+)\.[0-9]+$ ]] && version="${BASH_REMATCH[1]}" ;;
       ^) [[ "${version}" =~ ^([0-9]+) ]] && version="${BASH_REMATCH[1]}" ;;
     esac
+    trace_log "target" "${version}"
   else
     command -v npx &> /dev/null || abort "an active version of npx is required to use complex 'engine' ranges from package.json"
     trace_log "resolving" "${range}"
@@ -1016,10 +1017,31 @@ function display_nvmrc_version() {
 }
 
 #
+# Synopsis: display_engine_version [error-message]
+#
+
+function display_engine_version() {
+  local error_message="${1-package.json not found}"
+  local parent
+  parent="${PWD}"
+  while [[ -n "${parent}" ]]; do
+    if [[ -e "${parent}/package.json" ]]; then
+      display_package_engine_version "${parent}/package.json"
+    else
+      parent=${parent%/*}
+      continue
+    fi
+    break
+  done
+  [[ -n "${parent}" ]] || abort "${error_message}"
+}
+
+#
 # Synopsis: display_auto_version
 #
 
 function display_auto_version() {
+  # Search for a version control file first
   local parent
   parent="${PWD}"
   while [[ -n "${parent}" ]]; do
@@ -1029,25 +1051,27 @@ function display_auto_version() {
       display_file_node_version "${parent}/.node-version"
     elif [[ -e "${parent}/.nvmrc" ]]; then
       display_nvmrc_version "${parent}/.nvmrc"
-    elif [[ -e "${parent}/package.json" ]]; then
-      display_package_engine_version "${parent}/package.json"
     else
       parent=${parent%/*}
       continue
     fi
     break
   done
-  [[ -n "${parent}" ]] || abort "no file found for auto version"
+  # Fallback to package.json
+  [[ -n "${parent}" ]] || display_engine_version "no file found for auto version (.n-node-version, .node-version, .nvmrc, or package.json)"
 }
-
 #
 # Synopsis: display_latest_resolved_version version
 #
 
 function display_latest_resolved_version() {
   local version=${1}
+  # auto and engine make sense for local use and not much for ls-remote, so handled here rather than display_remote_versions
   if [[ "${version}" = "auto" ]]; then
     version="$(display_auto_version)" || return 2
+  fi
+  if [[ "${version}" = "engine" ]]; then
+    version="$(display_engine_version)" || return 2
   fi
   simple_version=${version#node/} # Only place supporting node/ [sic]
   if is_exact_numeric_version "${simple_version}"; then
@@ -1233,7 +1257,7 @@ function show_diagnostics() {
   printf "\nnode\n"
   if command -v node &> /dev/null; then
     command -v node && node --version
-    node -e 'if (process.versions.v8) console.log("JavaScript engine: v8"); if (process.versions.chakracore) console.log("JavaScript engine: chakracore")'
+    node -e 'if (process.versions.v8) console.log("JavaScript engine: v8");'
 
     printf "\nnpm\n"
     command -v npm && npm --version
