added functionality to set how and wether colors are outputted

diff --git a/bin/n b/bin/n
--- a/bin/n
+++ b/bin/n
@@ -19,15 +19,14 @@ parseColors() {
 		RED="\033[31m";
 		GREEN="\033[32m"
 		SPECIAL="\033[90m";
-	elif $1 == "nocolors"; then
+	elif [[ $1 == "nocolors" ]]; then
 		e=""
 		BLACK="";
 		RED="";
 		GREEN="";
 		SPECIAL="";
 	else
-		echo '$colors is incorrectly set in the config file. choices are: colors, colors+, nocolors'
-		exit
+		abort '$colors is incorrectly set in the config file. choices are: colors, colors+, nocolors'
 	fi
 }
 
@@ -36,7 +35,7 @@ parseColors() {
 #
 
 log() {
-  echo $e $SPECIAL"..."$BLACK $@
+  echo $e $SPECIAL"..."$BLACK" "$@
 }
 
 #
@@ -44,7 +43,7 @@ log() {
 #
 
 abort() {
-  echo $e $RED"Error: "$@$Black && exit 1
+  echo $e $RED"Error: $@"$BLACK && exit 1
 }
 
 # setup
@@ -136,7 +135,7 @@ display_versions() {
     local version=${dir##*/}
     local config=`test -f $dir/.config && cat $dir/.config`
     if test "$version" = "$active"; then
-      echo $e "  "$GREEN"ο"$BLACK $version $SPECIAL$config$BLACK
+      echo $e "  "$GREEN"ο"$BLACK" "$version" "$SPECIAL$config$BLACK
     else
       echo $e "    $version $SPECIAL$config$BLACK"
     fi
@@ -178,7 +177,7 @@ install_node() {
     # see if things are alright
     if test $? -gt 0; then
       rm $tarball
-      echo $e $RED"mError: installation failed"$BLACK
+      echo $e $RED"Error: installation failed"$BLACK
       echo $e "  node version $version does not exist,"
       echo $e "  n failed to fetch the tarball,"
       echo $e "  or tar failed. Try a different"
@@ -283,14 +282,15 @@ list_versions() {
     | sort -u -k 1,1n -k 2,2n -k 3,3n -t . \
     | awk '{ print "  " $1 }'`
 
+
   for v in $versions; do
     if test "$active" = "$v"; then
-      echo $e "  $GREENο$BLACK $v "
+      echo $e "  $GREEN""ο"$BLACK" $v "
     else
       if test -d $VERSIONS_DIR/$v; then
-        echo -e "  * $v "$BLACK
+        echo $e "  * $v"$BLACK
       else
-        echo -e "    $v"
+        echo $e "    $v"$BLACK
       fi
     fi
   done
